// Starter data: consolidated organization list and action plan.
// Loaded into the database automatically the first time the site runs.
export const SEED = {
 "orgs": {
  "aae": {
   "rank": 62,
   "name": "AAE",
   "aka": "Association of Association Executives",
   "tier": 3,
   "specialty": "International association leadership",
   "approach": "Supplier-associate route; congresses and education contributions.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "acae": {
   "rank": 43,
   "name": "ACAE",
   "aka": "Alabama Council of Association Executives",
   "tier": 2,
   "specialty": "Alabama association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "acced-i": {
   "rank": 66,
   "name": "ACCED-I",
   "aka": "",
   "tier": 4,
   "specialty": "Collegiate conference and event professionals",
   "approach": "Corporate membership or education when targeting university events.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "aci": {
   "rank": 77,
   "name": "American Conference Institute",
   "aka": "ACI",
   "tier": 4,
   "specialty": "Legal and regulatory conferences",
   "approach": "Only programs with a clear fit for leadership content.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "admei": {
   "rank": 53,
   "name": "ADMEI",
   "aka": "Association of Destination Management Executives International",
   "tier": 3,
   "specialty": "Destination management companies",
   "approach": "Build DMC relationships; explore supplier participation.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "aenc": {
   "rank": 25,
   "name": "AENC",
   "aka": "Association Executives of North Carolina",
   "tier": 2,
   "specialty": "North Carolina association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "aloha-sae": {
   "rank": 48,
   "name": "Aloha SAE",
   "aka": "Aloha Society of Association Executives",
   "tier": 2,
   "specialty": "Hawaii association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "amc-institute": {
   "rank": 6,
   "name": "AMC Institute",
   "aka": "AMCI",
   "tier": 1,
   "specialty": "Association management company executives",
   "approach": "Industry-partner membership; build relationships with AMCs that run many associations' conventions.",
   "notes": "One AMC relationship can unlock several convention stages.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "amps": {
   "rank": 20,
   "name": "AMPs",
   "aka": "Association of Meeting Professionals",
   "tier": 2,
   "specialty": "Washington-area meeting professionals",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "Find via the Association Leadership Coalition directory.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "apo": {
   "rank": 44,
   "name": "APO",
   "aka": "Association Professionals of Oklahoma",
   "tier": 2,
   "specialty": "Oklahoma association professionals",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "arsae": {
   "rank": 45,
   "name": "ASAE Arkansas",
   "aka": "Arkansas Society of Association Executives",
   "tier": 2,
   "specialty": "Arkansas association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "asae": {
   "rank": 1,
   "name": "ASAE",
   "aka": "American Society of Association Executives",
   "tier": 1,
   "specialty": "National association executives",
   "approach": "Industry-partner membership; attend the Annual Meeting; contribute education and content.",
   "notes": "Every source ranks this #1. Execs scout main-stage talent here.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "association-forum": {
   "rank": 5,
   "name": "Association Forum",
   "aka": "Chicago",
   "tier": 1,
   "specialty": "Chicagoland association leaders",
   "approach": "Membership; Holiday Showcase; education proposals.",
   "notes": "Chicago has the second-highest density of associations after DC.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "associations-north": {
   "rank": 22,
   "name": "Associations North",
   "aka": "",
   "tier": 2,
   "specialty": "Upper Midwest association professionals",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "associations-west": {
   "rank": 2,
   "name": "Associations West",
   "aka": "Formerly CalSAE",
   "tier": 1,
   "specialty": "Western association executives",
   "approach": "Join; submit ELEVATE education proposals; attend Seasonal Spectacular.",
   "notes": "Published ELEVATE proposal deadline in research: Sept 25, 2026. Verify on their site.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "azsae": {
   "rank": 31,
   "name": "AzSAE",
   "aka": "Arizona Society of Association Executives",
   "tier": 2,
   "specialty": "Arizona association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "caps": {
   "rank": 72,
   "name": "CAPS",
   "aka": "Canadian Association of Professional Speakers",
   "tier": 4,
   "specialty": "Canadian speaker development",
   "approach": "Peer referrals into the Canadian market.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "cema": {
   "rank": 51,
   "name": "CEMA",
   "aka": "Corporate Event Marketing Association",
   "tier": 3,
   "specialty": "Corporate event marketing leaders",
   "approach": "Explore supplier membership and programming; good fit for corporate work.",
   "notes": "Senior event marketers at large tech brands; substantial budgets.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "cesse": {
   "rank": 13,
   "name": "CESSE",
   "aka": "Council of Engineering and Scientific Society Executives",
   "tier": 1,
   "specialty": "Scientific and engineering association executives",
   "approach": "Pitch ACCESSE programming; explore partnerships.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "colorado-sae": {
   "rank": 30,
   "name": "Colorado SAE",
   "aka": "Colorado Society of Association Executives",
   "tier": 2,
   "specialty": "Colorado association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "connect": {
   "rank": 11,
   "name": "Connect Marketplace",
   "aka": "Informa Connect",
   "tier": 1,
   "specialty": "Hosted-buyer association marketplace",
   "approach": "Ask about speaker programming and supplier appointments before buying anything.",
   "notes": "Hosted buyers aren't automatically keynote buyers. Ask who selects and pays external speakers.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "csae-canada": {
   "rank": 21,
   "name": "CSAE",
   "aka": "Canadian Society of Association Executives",
   "tier": 2,
   "specialty": "Canadian association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "cvent-connect": {
   "rank": 55,
   "name": "Cvent CONNECT",
   "aka": "",
   "tier": 3,
   "specialty": "Event technology and meeting professionals",
   "approach": "Investigate speaker or partner opportunities. A conference, not an association.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "destinations-intl": {
   "rank": 67,
   "name": "Destinations International",
   "aka": "",
   "tier": 4,
   "specialty": "Destination marketing organizations",
   "approach": "Prioritize relevant local CVB relationships over broad exposure.",
   "notes": "CVBs sometimes recommend or sponsor speakers to win host-city bids.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "dfwae": {
   "rank": 37,
   "name": "DFWAE",
   "aka": "Dallas/Fort Worth Association Executives",
   "tier": 2,
   "specialty": "North Texas association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "eic": {
   "rank": 79,
   "name": "Events Industry Council",
   "aka": "EIC",
   "tier": 4,
   "specialty": "Industry standards and credentials",
   "approach": "Follow industry developments and CMP; not a core prospect.",
   "notes": "Umbrella of 30+ associations; no buyer marketplace.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "elx": {
   "rank": 73,
   "name": "ELX",
   "aka": "Event Leaders Exchange",
   "tier": 4,
   "specialty": "Senior corporate event leaders",
   "approach": "Explore partnership or contribution; access is selective.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "eo": {
   "rank": 58,
   "name": "EO",
   "aka": "Entrepreneurs' Organization",
   "tier": 3,
   "specialty": "Entrepreneur learning and leadership",
   "approach": "Target chapter learning programs and event organizers.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "espa": {
   "rank": 71,
   "name": "ESPA",
   "aka": "Event Service Professionals Association",
   "tier": 4,
   "specialty": "Convention and event services",
   "approach": "Service-provider relationships; referral only.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "essae": {
   "rank": 36,
   "name": "ESSAE",
   "aka": "Empire State Society of Association Executives",
   "tier": 2,
   "specialty": "New York State association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ficp": {
   "rank": 52,
   "name": "FICP",
   "aka": "Financial & Insurance Conference Professionals",
   "tier": 3,
   "specialty": "Financial and insurance meeting planners",
   "approach": "Check hospitality-partner eligibility; events generally need sponsorship.",
   "notes": "Some of the highest speaker-fee budgets.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "fsae": {
   "rank": 9,
   "name": "FSAE",
   "aka": "Florida Society of Association Executives",
   "tier": 1,
   "specialty": "Florida association executives",
   "approach": "Explore membership, annual conference and education slots.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "gsae": {
   "rank": 23,
   "name": "GSAE",
   "aka": "Georgia Society of Association Executives",
   "tier": 2,
   "specialty": "Georgia association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "gsf": {
   "rank": 78,
   "name": "Global Speakers Federation",
   "aka": "GSF",
   "tier": 4,
   "specialty": "Worldwide speaker associations",
   "approach": "International peer connections only.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "gsia": {
   "rank": 7,
   "name": "GSIA",
   "aka": "Global Speaking Industry Association; formerly IASB",
   "tier": 1,
   "specialty": "Speaker bureaus and booking agents",
   "approach": "Apply to the GSIAtalks showcase; separately assess bureau-membership eligibility for Speak About AI.",
   "notes": "2026 showcase application closed July 1. Watch for the next cycle. Eligibility depends on revenue and business-structure criteria.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "hsmai": {
   "rank": 69,
   "name": "HSMAI",
   "aka": "Hospitality Sales and Marketing Association International",
   "tier": 4,
   "specialty": "Hospitality sales and marketing",
   "approach": "Only for hospitality-specific topics.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "iaee": {
   "rank": 17,
   "name": "IAEE + Northern California chapter",
   "aka": "International Association of Exhibitions and Events",
   "tier": 1,
   "specialty": "Exhibition and trade-show organizers",
   "approach": "Organizer relationships; fits the trade-show offering.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "iapco": {
   "rank": 63,
   "name": "IAPCO",
   "aka": "International Association of Professional Congress Organisers",
   "tier": 3,
   "specialty": "Professional congress organizers",
   "approach": "Research member firms and partnerships; membership isn't a speaker route.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "iavm": {
   "rank": 70,
   "name": "IAVM",
   "aka": "International Association of Venue Managers",
   "tier": 4,
   "specialty": "Public assembly venue management",
   "approach": "Venue relationships; indirect access to association buyers.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ibtm": {
   "rank": 64,
   "name": "IBTM World",
   "aka": "",
   "tier": 3,
   "specialty": "International meetings marketplace",
   "approach": "Exhibit or present when international expansion is a priority.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "icca": {
   "rank": 61,
   "name": "ICCA",
   "aka": "International Congress and Convention Association",
   "tier": 3,
   "specialty": "International association congresses",
   "approach": "Supplier access when pursuing international congresses.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ilea": {
   "rank": 16,
   "name": "ILEA + Northern California chapter",
   "aka": "International Live Events Association",
   "tier": 1,
   "specialty": "Creative live-event professionals",
   "approach": "Producer relationships; opportunities to demo hosting and entertainment.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "illinois-sae": {
   "rank": 35,
   "name": "Illinois SAE",
   "aka": "Illinois Society of Association Executives",
   "tier": 2,
   "specialty": "Illinois association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "imex": {
   "rank": 12,
   "name": "IMEX America",
   "aka": "",
   "tier": 1,
   "specialty": "Global meetings industry marketplace",
   "approach": "Explore education sessions, partnerships, exhibiting. Not a membership.",
   "notes": "Hosted-buyer program is for people commissioning events, not sellers.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "iqpc": {
   "rank": 74,
   "name": "IQPC",
   "aka": "",
   "tier": 4,
   "specialty": "Commercial industry conferences",
   "approach": "Pitch individual producers; confirm a paid keynote exists.",
   "notes": "For-profit model; mostly sponsor-backed sessions.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "isae": {
   "rank": 34,
   "name": "ISAE",
   "aka": "Indiana Society of Association Executives",
   "tier": 2,
   "specialty": "Indiana association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ksae": {
   "rank": 41,
   "name": "KSAE",
   "aka": "Kentucky Society of Association Executives",
   "tier": 2,
   "specialty": "Kentucky association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "lgbt-mpa": {
   "rank": 50,
   "name": "LGBT MPA",
   "aka": "LGBTQ+ Meeting Professionals Association",
   "tier": 3,
   "specialty": "LGBTQ+ meeting professionals and allies",
   "approach": "Supplier or ally-supplier membership; participate meaningfully.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "lsae": {
   "rank": 42,
   "name": "LSAE",
   "aka": "Louisiana Society of Association Executives",
   "tier": 2,
   "specialty": "Louisiana association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "marcus-evans": {
   "rank": 76,
   "name": "Marcus Evans",
   "aka": "",
   "tier": 4,
   "specialty": "Commercial executive summits",
   "approach": "Approach producers of well-matched summits; qualify topic and fee.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "masae": {
   "rank": 29,
   "name": "MASAE",
   "aka": "Mid-Atlantic Society of Association Executives",
   "tier": 2,
   "specialty": "Mid-Atlantic association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "meetings-show": {
   "rank": 65,
   "name": "The Meetings Show",
   "aka": "",
   "tier": 3,
   "specialty": "UK and international meeting buyers",
   "approach": "Speak or exhibit as part of a deliberate UK campaign.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "meetings-today": {
   "rank": 19,
   "name": "Meetings Today LIVE!",
   "aka": "",
   "tier": 1,
   "specialty": "Regional hosted-planner events",
   "approach": "Approach the education team about presenting.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "metro-nysae": {
   "rank": 26,
   "name": "Metro NYSAE",
   "aka": "Metro New York Society of Association Executives",
   "tier": 2,
   "specialty": "NYC-area association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "mpi": {
   "rank": 4,
   "name": "MPI + Northern California chapter",
   "aka": "Meeting Professionals International; also Sacramento/Sierra Nevada chapter",
   "tier": 1,
   "specialty": "Meeting and event professionals",
   "approach": "Join locally; submit the chapter speaker form; investigate ACE.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "msae": {
   "rank": 28,
   "name": "MSAE",
   "aka": "Michigan Society of Association Executives",
   "tier": 2,
   "specialty": "Michigan association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "mssae": {
   "rank": 47,
   "name": "MSAE Mississippi",
   "aka": "Mississippi Society of Association Executives",
   "tier": 2,
   "specialty": "Mississippi association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "nace": {
   "rank": 68,
   "name": "NACE",
   "aka": "National Association for Catering and Events",
   "tier": 4,
   "specialty": "Catering and special events",
   "approach": "Entertainment referrals more than keynotes.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ncbmp": {
   "rank": 14,
   "name": "NCBMP",
   "aka": "National Coalition of Black Meeting Professionals",
   "tier": 1,
   "specialty": "Black meeting professionals and allies",
   "approach": "Supplier participation, conference programming, sustained relationships.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "nesae": {
   "rank": 27,
   "name": "NESAE",
   "aka": "New England Society of Association Executives",
   "tier": 2,
   "specialty": "New England association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "nmsae": {
   "rank": 46,
   "name": "NMSAE",
   "aka": "New Mexico Society of Association Executives",
   "tier": 2,
   "specialty": "New Mexico association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "northstar": {
   "rank": 8,
   "name": "Northstar Meetings Group",
   "aka": "Destination California, Association Summits",
   "tier": 1,
   "specialty": "Hosted meeting-planner events",
   "approach": "Submit speaker proposals through the year-round portal.",
   "notes": "Portal provides travel, hospitality and a modest honorarium.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "nsa": {
   "rank": 15,
   "name": "NSA + Northern California chapter",
   "aka": "National Speakers Association",
   "tier": 1,
   "specialty": "Speaker development and peer referrals",
   "approach": "Build referral relationships; use the directory; ask about future showcases.",
   "notes": "Peer network more than a buyer channel. Last NorCal showcase found was May 2023.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "osap": {
   "rank": 32,
   "name": "OSAP",
   "aka": "Ohio Society of Association Professionals",
   "tier": 2,
   "specialty": "Ohio association professionals",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "pasae": {
   "rank": 38,
   "name": "PASAE",
   "aka": "Pennsylvania Society for Association Excellence",
   "tier": 2,
   "specialty": "Pennsylvania association professionals",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "pcma": {
   "rank": 3,
   "name": "PCMA + Northern California chapter",
   "aka": "Professional Convention Management Association",
   "tier": 1,
   "specialty": "Convention and conference professionals",
   "approach": "Supplier membership; local chapter education; Convening Leaders.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "questex": {
   "rank": 75,
   "name": "Questex / ExL Events",
   "aka": "",
   "tier": 4,
   "specialty": "Commercial industry conferences",
   "approach": "Target relevant individual events, not a membership.",
   "notes": "ExL Events is not EXL Services. Questex acquired ExL.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "rcma": {
   "rank": 60,
   "name": "RCMA",
   "aka": "Religious Conference Management Association",
   "tier": 3,
   "specialty": "Religious conferences and meetings",
   "approach": "Supplier membership; explore EMERGE and planner relationships.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "scsae": {
   "rank": 40,
   "name": "SCSAE",
   "aka": "South Carolina Society of Association Executives",
   "tier": 2,
   "specialty": "South Carolina association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "sgmp": {
   "rank": 59,
   "name": "SGMP + Golden State chapter",
   "aka": "Society of Government Meeting Professionals",
   "tier": 3,
   "specialty": "Government meeting professionals",
   "approach": "Chapter education and supplier participation; qualify each opportunity.",
   "notes": "Fees often capped by per diem and procurement limits.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "site": {
   "rank": 54,
   "name": "SITE + Northern California chapter",
   "aka": "Society for Incentive Travel Excellence",
   "tier": 3,
   "specialty": "Incentive travel professionals",
   "approach": "Local relationships; incentive-program hosting and entertainment.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "smart-meetings": {
   "rank": 18,
   "name": "Smart Meetings / Smart Events",
   "aka": "",
   "tier": 1,
   "specialty": "Hosted meeting-planner networking",
   "approach": "Pitch educational sessions; evaluate supplier options separately.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "spin": {
   "rank": 49,
   "name": "SPIN",
   "aka": "Senior Planners Industry Network",
   "tier": 3,
   "specialty": "Experienced meeting planners",
   "approach": "Suppliers join as year-round sponsors, not planner members.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "tnsae": {
   "rank": 39,
   "name": "TNSAE",
   "aka": "Tennessee Society of Association Executives",
   "tier": 2,
   "specialty": "Tennessee association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "tsae": {
   "rank": 10,
   "name": "TSAE",
   "aka": "Texas Society of Association Executives",
   "tier": 1,
   "specialty": "Texas association executives",
   "approach": "Submit a speaking proposal; separate promotional appearances from paid bookings.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "vistage": {
   "rank": 56,
   "name": "Vistage",
   "aka": "",
   "tier": 3,
   "specialty": "Executive peer-group learning",
   "approach": "Secure a Chair relationship or invitation; onboarding has access restrictions.",
   "notes": "Paid speaker circuit for CEO peer groups.",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "vsae": {
   "rank": 24,
   "name": "VSAE",
   "aka": "Virginia Society of Association Executives",
   "tier": 2,
   "specialty": "Virginia association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "wsae": {
   "rank": 33,
   "name": "WSAE",
   "aka": "Wisconsin Society of Association Executives",
   "tier": 2,
   "specialty": "Wisconsin association executives",
   "approach": "Pitch a useful session and identify buyers first; buy membership selectively.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  },
  "ypo": {
   "rank": 57,
   "name": "YPO",
   "aka": "Young Presidents' Organization",
   "tier": 3,
   "specialty": "Chief executive leadership community",
   "approach": "Approach as a speaker through relationships, not a membership purchase.",
   "notes": "",
   "status": "Not started",
   "nextAction": "",
   "nextDate": "",
   "website": ""
  }
 },
 "tasks": {
  "t01": {
   "title": "Verify the Associations West ELEVATE proposal deadline and requirements",
   "phase": "This week",
   "due": "2026-09-24",
   "orgId": "associations-west",
   "notes": "Research lists Sept 25, 2026. Last year's window closed Sept 5, so confirm it's still open.",
   "done": false,
   "order": 1
  },
  "t02": {
   "title": "Submit an Associations West ELEVATE education proposal",
   "phase": "This week",
   "due": "2026-09-25",
   "orgId": "associations-west",
   "notes": "Blind review: keep speaker and company names out of the title, description and objectives.",
   "done": false,
   "order": 2
  },
  "t03": {
   "title": "Submit the MPI Northern California speaker form",
   "phase": "This week",
   "due": "2026-10-02",
   "orgId": "mpi",
   "notes": "",
   "done": false,
   "order": 3
  },
  "t04": {
   "title": "Submit a proposal to Northstar's year-round speaker portal",
   "phase": "This week",
   "due": "2026-10-02",
   "orgId": "northstar",
   "notes": "",
   "done": false,
   "order": 4
  },
  "t05": {
   "title": "Set a reminder for the next GSIAtalks showcase application window",
   "phase": "This week",
   "due": "2026-10-02",
   "orgId": "gsia",
   "notes": "2026 window closed July 1.",
   "done": false,
   "order": 5
  },
  "t06": {
   "title": "Write a planner-facing session pitch for each speaker",
   "phase": "Foundation",
   "due": "2026-10-09",
   "orgId": "",
   "notes": "Teach planners something useful while demonstrating the keynote.",
   "done": false,
   "order": 6
  },
  "t07": {
   "title": "Prepare one-sheets and demo reel links for each speaker",
   "phase": "Foundation",
   "due": "2026-10-09",
   "orgId": "",
   "notes": "",
   "done": false,
   "order": 7
  },
  "t08": {
   "title": "Write the pre-purchase qualification checklist",
   "phase": "Foundation",
   "due": "2026-10-09",
   "orgId": "",
   "notes": "Who attends, who actually selects speakers, stage time included, follow-up allowed, what success looks like.",
   "done": false,
   "order": 8
  },
  "t09": {
   "title": "Check GSIA bureau-membership eligibility for Speak About AI",
   "phase": "Foundation",
   "due": "2026-10-16",
   "orgId": "gsia",
   "notes": "",
   "done": false,
   "order": 9
  },
  "t10": {
   "title": "Join ASAE as an industry partner",
   "phase": "Memberships",
   "due": "2026-10-23",
   "orgId": "asae",
   "notes": "",
   "done": false,
   "order": 10
  },
  "t11": {
   "title": "Join Associations West",
   "phase": "Memberships",
   "due": "2026-10-23",
   "orgId": "associations-west",
   "notes": "",
   "done": false,
   "order": 11
  },
  "t12": {
   "title": "Join PCMA and the Northern California chapter as a supplier",
   "phase": "Memberships",
   "due": "2026-10-30",
   "orgId": "pcma",
   "notes": "",
   "done": false,
   "order": 12
  },
  "t13": {
   "title": "Join MPI Northern California",
   "phase": "Memberships",
   "due": "2026-10-30",
   "orgId": "mpi",
   "notes": "",
   "done": false,
   "order": 13
  },
  "t14": {
   "title": "Attend a first chapter event at PCMA NorCal and MPI NorCal",
   "phase": "Memberships",
   "due": "2026-11-13",
   "orgId": "",
   "notes": "",
   "done": false,
   "order": 14
  },
  "t15": {
   "title": "Pitch Association Forum about Holiday Showcase and education slots",
   "phase": "Expand outreach",
   "due": "2026-10-16",
   "orgId": "association-forum",
   "notes": "",
   "done": false,
   "order": 15
  },
  "t16": {
   "title": "Identify three AMCs through AMC Institute and reach out",
   "phase": "Expand outreach",
   "due": "2026-10-30",
   "orgId": "amc-institute",
   "notes": "",
   "done": false,
   "order": 16
  },
  "t17": {
   "title": "Submit a TSAE speaking proposal",
   "phase": "Expand outreach",
   "due": "2026-10-30",
   "orgId": "tsae",
   "notes": "",
   "done": false,
   "order": 17
  },
  "t18": {
   "title": "Ask Connect Marketplace which buyers select and pay speakers",
   "phase": "Expand outreach",
   "due": "2026-10-30",
   "orgId": "connect",
   "notes": "Don't buy a package until this is answered.",
   "done": false,
   "order": 18
  },
  "t19": {
   "title": "Ask IMEX America about education session slots",
   "phase": "Expand outreach",
   "due": "2026-11-06",
   "orgId": "imex",
   "notes": "",
   "done": false,
   "order": 19
  },
  "t20": {
   "title": "Pitch CESSE's ACCESSE programming",
   "phase": "Expand outreach",
   "due": "2026-11-06",
   "orgId": "cesse",
   "notes": "",
   "done": false,
   "order": 20
  },
  "t21": {
   "title": "Pitch education teams at Smart Meetings and Meetings Today LIVE!",
   "phase": "Expand outreach",
   "due": "2026-11-13",
   "orgId": "smart-meetings",
   "notes": "",
   "done": false,
   "order": 21
  },
  "t22": {
   "title": "Pick three state societies from the Association Leadership Coalition directory and pitch them",
   "phase": "Expand outreach",
   "due": "2026-11-20",
   "orgId": "",
   "notes": "",
   "done": false,
   "order": 22
  },
  "t23": {
   "title": "Weekly: log every outreach and clear due follow-ups",
   "phase": "Ongoing rhythm",
   "due": "",
   "orgId": "",
   "notes": "",
   "done": false,
   "order": 23
  },
  "t24": {
   "title": "Monthly: review the pipeline and drop channels with no qualified buyers",
   "phase": "Ongoing rhythm",
   "due": "",
   "orgId": "",
   "notes": "",
   "done": false,
   "order": 24
  }
 }
};
